# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test2.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_komunikator(object):
    def setupUi(self, komunikator):
        komunikator.setObjectName("komunikator")
        komunikator.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(komunikator)
        self.centralwidget.setObjectName("centralwidget")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(-1, -1, 801, 521))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 799, 519))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.monitorOut = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        self.monitorOut.setGeometry(QtCore.QRect(-5, 1, 811, 521))
        self.monitorOut.setObjectName("monitorOut")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.bledyCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.bledyCheck.setGeometry(QtCore.QRect(0, 530, 92, 23))
        self.bledyCheck.setObjectName("bledyCheck")
        self.komCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.komCheck.setGeometry(QtCore.QRect(90, 530, 171, 23))
        self.komCheck.setObjectName("komCheck")
        self.archiwizuj = QtWidgets.QPushButton(self.centralwidget)
        self.archiwizuj.setGeometry(QtCore.QRect(680, 530, 89, 25))
        self.archiwizuj.setLocale(QtCore.QLocale(QtCore.QLocale.Polish, QtCore.QLocale.Poland))
        self.archiwizuj.setObjectName("archiwizuj")
        komunikator.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(komunikator)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        komunikator.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(komunikator)
        self.statusbar.setObjectName("statusbar")
        komunikator.setStatusBar(self.statusbar)

        self.retranslateUi(komunikator)
        QtCore.QMetaObject.connectSlotsByName(komunikator)

    def retranslateUi(self, komunikator):
        _translate = QtCore.QCoreApplication.translate
        komunikator.setWindowTitle(_translate("komunikator", "Komunikator"))
        self.bledyCheck.setText(_translate("komunikator", "Błędy"))
        self.komCheck.setText(_translate("komunikator", "Raporty z komunikacji"))
        self.archiwizuj.setText(_translate("komunikator", "Archiwizuj"))
